# Generated by Django 5.0.7 on 2026-05-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('company_branch', models.CharField(blank=True, choices=[('Chicago', 'Chicago'), ('Amsterdam', 'Amsterdam'), ('Bucharest', 'Bucharest')], max_length=70)),
                ('department', models.CharField(blank=True, max_length=70)),
                ('position', models.CharField(blank=True, max_length=70)),
                ('personal_phone', models.CharField(blank=True, max_length=70)),
                ('personal_mail', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=70)),
                ('photo', models.ImageField(blank=True, upload_to='employee_photos/%Y/%m/%d')),
                ('level_of_english', models.CharField(blank=True, choices=[('Weak', 'Weak'), ('Communicative', 'Communicative'), ('Fluent', 'Fluent')], max_length=70)),
                ('native_language', models.CharField(blank=True, max_length=70)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'employee_id')},
            },
        ),
    ]
